// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Models.proto

package services

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//商品模型
type ProdModel struct {
	ProdId               int32    `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	ProdName             string   `protobuf:"bytes,2,opt,name=prod_name,json=prodName,proto3" json:"prod_name,omitempty"`
	ProdPrice            float32  `protobuf:"fixed32,3,opt,name=prod_price,json=prodPrice,proto3" json:"prod_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b05f67b8e9f86a, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

func (m *ProdModel) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

func (m *ProdModel) GetProdPrice() float32 {
	if m != nil {
		return m.ProdPrice
	}
	return 0
}

//主订单模型
type OrderMain struct {
	OrderId              int32                `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo              string               `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId               int32                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderMoney           float32              `protobuf:"fixed32,4,opt,name=order_money,json=orderMoney,proto3" json:"order_money,omitempty"`
	OrderTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	OrderDetails         []*OrderDetail       `protobuf:"bytes,6,rep,name=order_details,json=orderDetails,proto3" json:"order_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderMain) Reset()         { *m = OrderMain{} }
func (m *OrderMain) String() string { return proto.CompactTextString(m) }
func (*OrderMain) ProtoMessage()    {}
func (*OrderMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b05f67b8e9f86a, []int{1}
}

func (m *OrderMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMain.Unmarshal(m, b)
}
func (m *OrderMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMain.Marshal(b, m, deterministic)
}
func (m *OrderMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMain.Merge(m, src)
}
func (m *OrderMain) XXX_Size() int {
	return xxx_messageInfo_OrderMain.Size(m)
}
func (m *OrderMain) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMain.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMain proto.InternalMessageInfo

func (m *OrderMain) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderMain) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *OrderMain) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderMain) GetOrderMoney() float32 {
	if m != nil {
		return m.OrderMoney
	}
	return 0
}

func (m *OrderMain) GetOrderTime() *timestamp.Timestamp {
	if m != nil {
		return m.OrderTime
	}
	return nil
}

func (m *OrderMain) GetOrderDetails() []*OrderDetail {
	if m != nil {
		return m.OrderDetails
	}
	return nil
}

//子订单模型
type OrderDetail struct {
	DetailId             int32    `protobuf:"varint,1,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	OrderNo              string   `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ProdId               int32    `protobuf:"varint,3,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	ProdPrice            float32  `protobuf:"fixed32,4,opt,name=prod_price,json=prodPrice,proto3" json:"prod_price,omitempty"`
	ProdNum              int32    `protobuf:"varint,5,opt,name=prod_num,json=prodNum,proto3" json:"prod_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b05f67b8e9f86a, []int{2}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetDetailId() int32 {
	if m != nil {
		return m.DetailId
	}
	return 0
}

func (m *OrderDetail) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *OrderDetail) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

func (m *OrderDetail) GetProdPrice() float32 {
	if m != nil {
		return m.ProdPrice
	}
	return 0
}

func (m *OrderDetail) GetProdNum() int32 {
	if m != nil {
		return m.ProdNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "services.ProdModel")
	proto.RegisterType((*OrderMain)(nil), "services.OrderMain")
	proto.RegisterType((*OrderDetail)(nil), "services.OrderDetail")
}

func init() { proto.RegisterFile("Models.proto", fileDescriptor_96b05f67b8e9f86a) }

var fileDescriptor_96b05f67b8e9f86a = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x6a, 0xe3, 0x30,
	0x10, 0x8d, 0xe3, 0x38, 0xb1, 0xc7, 0xd9, 0x3d, 0x08, 0x96, 0xf5, 0x66, 0x29, 0x35, 0x81, 0x82,
	0xa1, 0xe0, 0x40, 0x7a, 0x6a, 0x2f, 0x85, 0xd0, 0x4b, 0x0e, 0x49, 0x83, 0xe8, 0x3d, 0x55, 0x22,
	0x35, 0x08, 0x2c, 0xcb, 0x48, 0x76, 0xa0, 0xb7, 0x7e, 0x46, 0xbf, 0xb5, 0x87, 0x52, 0x24, 0xd5,
	0xb8, 0xe9, 0xa5, 0xc7, 0x37, 0x6f, 0xe6, 0xcd, 0xcc, 0x7b, 0x30, 0x5e, 0x49, 0xca, 0x0a, 0x9d,
	0x57, 0x4a, 0xd6, 0x12, 0x85, 0x9a, 0xa9, 0x23, 0xdf, 0x33, 0x3d, 0x39, 0x3f, 0x48, 0x79, 0x28,
	0xd8, 0xcc, 0xd6, 0x77, 0xcd, 0xd3, 0xac, 0xe6, 0x82, 0xe9, 0x9a, 0x88, 0xca, 0xb5, 0x4e, 0x7e,
	0x1f, 0x49, 0xc1, 0x29, 0xa9, 0x99, 0xc3, 0xd3, 0x47, 0x88, 0x36, 0x4a, 0x52, 0x2b, 0x87, 0xfe,
	0xc2, 0xa8, 0x52, 0x92, 0x6e, 0x39, 0x4d, 0xbc, 0xd4, 0xcb, 0x02, 0x3c, 0x34, 0x70, 0x49, 0xd1,
	0x7f, 0x88, 0x2c, 0x51, 0x12, 0xc1, 0x92, 0x7e, 0xea, 0x65, 0x11, 0x0e, 0x4d, 0x61, 0x4d, 0x04,
	0x43, 0x67, 0x00, 0x96, 0xac, 0x14, 0xdf, 0xb3, 0xc4, 0x4f, 0xbd, 0xac, 0x8f, 0x6d, 0xfb, 0xc6,
	0x14, 0xa6, 0xef, 0x1e, 0x44, 0xf7, 0x8a, 0x32, 0xb5, 0x22, 0xbc, 0x44, 0xff, 0x20, 0x94, 0x06,
	0x74, 0x3b, 0x46, 0x16, 0x2f, 0x69, 0x47, 0x95, 0xf2, 0x73, 0x87, 0xa3, 0xd6, 0xd2, 0x1c, 0xd6,
	0x68, 0x37, 0xe4, 0xbb, 0xc3, 0x0c, 0x5c, 0x52, 0x74, 0x09, 0xb1, 0x9b, 0x11, 0xb2, 0x64, 0xcf,
	0xc9, 0xc0, 0x2c, 0x5f, 0xc0, 0xdb, 0x62, 0x04, 0xc1, 0x45, 0xaf, 0xf7, 0x72, 0x8b, 0xc1, 0xd2,
	0x2b, 0xc3, 0xa2, 0x6b, 0x70, 0x68, 0x6b, 0x4c, 0x49, 0x82, 0xd4, 0xcb, 0xe2, 0xf9, 0x24, 0x77,
	0x8e, 0xe5, 0xad, 0x63, 0xf9, 0x43, 0xeb, 0x18, 0x8e, 0x6c, 0xb7, 0xc1, 0xe8, 0x06, 0x7e, 0xb9,
	0x51, 0xca, 0x6a, 0xc2, 0x0b, 0x9d, 0x0c, 0x53, 0x3f, 0x8b, 0xe7, 0x7f, 0xf2, 0xd6, 0xf9, 0xdc,
	0xbe, 0x78, 0x67, 0x59, 0x3c, 0x96, 0x1d, 0xd0, 0xd3, 0x57, 0x0f, 0xe2, 0x2f, 0xac, 0x31, 0xd3,
	0xa9, 0x74, 0x1e, 0x84, 0xae, 0xf0, 0xa3, 0x09, 0x6d, 0x3a, 0xfe, 0x49, 0x3a, 0xa7, 0x01, 0x0c,
	0xbe, 0x05, 0x60, 0x24, 0x5d, 0x78, 0x8d, 0xb0, 0x4f, 0x07, 0xd8, 0xea, 0xac, 0x1b, 0xb1, 0x1b,
	0xda, 0xaf, 0xaf, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xe1, 0x0b, 0xad, 0x4f, 0x02, 0x00,
	0x00,
}
