// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Orders.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e258ede2b56f8bf, []int{0}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderResponse)(nil), "services.OrderResponse")
}

func init() { proto.RegisterFile("Orders.proto", fileDescriptor_6e258ede2b56f8bf) }

var fileDescriptor_6e258ede2b56f8bf = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x46, 0xad, 0x43, 0xad, 0xa1, 0x2e, 0x11, 0xb4, 0x14, 0x07, 0xe9, 0xe4, 0xd4, 0x82, 0x6e,
	0x6e, 0xae, 0x42, 0x15, 0xea, 0x2f, 0x38, 0xed, 0x51, 0x02, 0x35, 0x17, 0x72, 0x51, 0xff, 0xbe,
	0x10, 0x93, 0xc5, 0xf1, 0xbd, 0x84, 0xfb, 0x9e, 0xc8, 0xaf, 0xb6, 0x47, 0xcb, 0xb5, 0xb1, 0xe4,
	0x48, 0x66, 0x8c, 0xf6, 0xad, 0x1e, 0xc8, 0xe5, 0x66, 0x20, 0x1a, 0x46, 0x6c, 0xc0, 0xa8, 0x06,
	0xb4, 0x26, 0x07, 0x4e, 0x91, 0x0e, 0xff, 0xca, 0xbc, 0xa5, 0x1e, 0xc7, 0x40, 0xd5, 0x49, 0x2c,
	0xfc, 0x95, 0x0e, 0xd9, 0x90, 0x66, 0x94, 0x2b, 0x91, 0xb2, 0x03, 0xf7, 0xe2, 0x22, 0xd9, 0x26,
	0xbb, 0x79, 0x17, 0x48, 0x16, 0x62, 0xf6, 0x44, 0x66, 0x18, 0xb0, 0x98, 0xfa, 0x87, 0x88, 0xfb,
	0x73, 0x08, 0xb9, 0xfd, 0xf6, 0xe5, 0x51, 0x64, 0x17, 0xfc, 0x78, 0x25, 0x97, 0x75, 0xac, 0xaa,
	0xbd, 0x68, 0x41, 0xe9, 0x72, 0xfd, 0x27, 0xe3, 0x76, 0x35, 0xb9, 0xa7, 0xbe, 0xea, 0xf0, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0xda, 0xf9, 0xa3, 0xdb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	NewOrder(ctx context.Context, in *OrderMain, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) NewOrder(ctx context.Context, in *OrderMain, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/services.OrderService/NewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	NewOrder(context.Context, *OrderMain) (*OrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) NewOrder(ctx context.Context, req *OrderMain) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_NewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).NewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.OrderService/NewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).NewOrder(ctx, req.(*OrderMain))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOrder",
			Handler:    _OrderService_NewOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Orders.proto",
}
